export const dataTypes = {
  FETCHED_DATA: "FETCHED_DATA",
  PAGINATE_DATA: "PAGINATE_DATA",
  SORT_BY_ALPHABET: "SORT_BY_ALPHABET",
  FILTERED_TEMPLATES: "FILTERED_TEMPLATES",
  FILTERED_CATEGORY: "FIlTERED_CATEGORY",
};